In [1]:
import torch

## Tensors

In [16]:
scalar = torch.tensor(1)
scalar

tensor(1)

In [17]:
vector = torch.tensor([4,2])
vector

tensor([4, 2])

In [18]:
MATRIX = torch.tensor([[1,2],[3,4]])
MATRIX.shape

torch.Size([2, 2])

In [19]:
MATRIX.ndim

2

In [20]:
TENSOR = torch.tensor([[[1,2,3],[4,3,6],[5,3,6]],[[2,3,5],[5,2,5],[5,3,1]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 3, 6],
         [5, 3, 6]],

        [[2, 3, 5],
         [5, 2, 5],
         [5, 3, 1]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([2, 3, 3])

In [23]:
TENSOR[1]

tensor([[2, 3, 5],
        [5, 2, 5],
        [5, 3, 1]])

## Random Tensors

In [8]:
random_tensor = torch.rand(10,3,4)
random_tensor

tensor([[[0.7287, 0.5312, 0.0291, 0.9583],
         [0.6488, 0.9880, 0.9994, 0.1849],
         [0.1875, 0.4111, 0.5235, 0.4375]],

        [[0.9613, 0.5101, 0.6067, 0.1884],
         [0.2368, 0.8167, 0.1636, 0.5265],
         [0.3799, 0.9259, 0.8719, 0.9605]],

        [[0.9000, 0.5029, 0.0959, 0.7755],
         [0.3451, 0.3844, 0.2913, 0.2991],
         [0.4621, 0.0249, 0.8308, 0.8520]],

        [[0.1815, 0.9679, 0.6459, 0.2607],
         [0.2521, 0.3679, 0.5903, 0.6221],
         [0.1485, 0.4994, 0.6926, 0.1747]],

        [[0.6724, 0.8543, 0.2096, 0.4346],
         [0.8947, 0.9709, 0.7695, 0.4772],
         [0.3451, 0.0073, 0.4553, 0.1404]],

        [[0.5268, 0.7811, 0.0127, 0.8157],
         [0.4349, 0.6568, 0.9297, 0.7771],
         [0.8076, 0.8116, 0.1163, 0.8071]],

        [[0.4538, 0.3743, 0.9536, 0.9278],
         [0.7395, 0.2835, 0.8415, 0.6373],
         [0.5490, 0.8199, 0.3380, 0.3012]],

        [[0.0068, 0.5493, 0.5783, 0.2776],
         [0.5959, 0.1131, 0.2357, 0.8702

In [9]:
random_tensor.ndim

3

In [11]:
random_image_tensor = torch.rand(3,224,224)
random_image_tensor.shape

torch.Size([3, 224, 224])

In [22]:
zeroes = torch.zeros(size=(3,3))
zeroes

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [23]:
zeroes * TENSOR[1]

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [30]:
torch.arange(1,999,99)

tensor([  1, 100, 199, 298, 397, 496, 595, 694, 793, 892, 991])

In [44]:
torch.tensor((3,4),
             dtype=None,
             device='cpu',
             requires_grad = False
            )

tensor([3, 4])

In [47]:
torch.cuda.is_available()

False

In [48]:
torch.cuda.device_count()

0