In [3]:
import torch

In [8]:
scalar = torch.tensor(1)
scalar

tensor(1)

In [9]:
vector = torch.tensor([4,2])
vector

tensor([4, 2])

In [24]:
MATRIX = torch.tensor([[1,2],[3,4]])
MATRIX.shape

torch.Size([2, 2])

In [25]:
MATRIX.ndim

2

In [17]:
TENSOR = torch.tensor([[[1,2,3],[4,3,6],[5,3,6]],[[2,3,5],[5,2,5],[5,3,1]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 3, 6],
         [5, 3, 6]],

        [[2, 3, 5],
         [5, 2, 5],
         [5, 3, 1]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([2, 3, 3])

In [23]:
TENSOR[1]

tensor([[2, 3, 5],
        [5, 2, 5],
        [5, 3, 1]])